### PR TITLE
chore: migrate from tap to node:test and c8

### PR DESCRIPTION
**Pull request by dancastillo**
#### Checklist

This PR migrates from `tap` to `node:test` and `c8`

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — COMMENTED** [review]
Since this is a library and not a Fastify plugin, it's tested on Node 18 as well

You can use `node:assert` instead of `t.assert`

**Comment by dancastillo** [comment]
@gurgunday I added in `@matteo.collina/tspl` so we can have test plan. Lmk if that is okay or should use `node:assert`

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]
Cool!

**Review by gurgunday — APPROVED** [review]
Cool indeed!

**Pull request merged**
